name: Continuous Delivery

on:
  workflow_call:

jobs:
    EC2:
      runs-on: ubuntu-latest
      steps:
      - name: current version
        uses: actions/checkout@v2
        
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        
      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          LOCAL_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: /home/${{ secrets.REMOTE_USER }}
          EXCLUDE: "/dist/, /node_modules/, /*"
      - name: exec remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            export HOST=${{ secrets.DB_HOST }}
            export USER=${{ secrets.DB_USER }}
            export PASSWORD=${{ secrets.DB_PASSWORD }}
            export DBNAME=${{ secrets.DB_NAME }}
            export DBPORT=${{ secrets.DB_PORT }}
            export PORT=8000
            chmod +x main
            nohup ./main > nohup.out 2> nohup.err < & dev/null &
